title: Kimnamu
description: Kimnamu Blog

url: http://kimnamu.github.io
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Research
    url: /research
  - title: Development
    url: /development

social:
  github: kimnamu
  # twitter: brianmaierjr
  # facebook: brianmaierjr
  email: jihoon.lucas.kim@gmail.com
  linkedin: jihoonlucaskim

# google_analytics: "UA-58263416-1"

disqus:
    shortname: kimnamu
